boot.o: boot.S multiboot.h x86_desc.h types.h
handlers.o: handlers.S handlers.h
x86_desc.o: x86_desc.S x86_desc.h types.h
file.o: file.c file.h types.h syscall.h lib.h paging.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h handlers.h keyboard.h rtc.h \
  syscall.h file.h paging.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h keyboard.h rtc.h idt.h paging.h file.h syscall.h terminal.h \
  schedule.h mouse.h signal.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h terminal.h \
  paging.h syscall.h file.h mouse.h signal.h idt.h x86_desc.h
lib.o: lib.c lib.h types.h keyboard.h terminal.h paging.h syscall.h \
  file.h
mouse.o: mouse.c mouse.h lib.h types.h keyboard.h i8259.h terminal.h \
  paging.h syscall.h file.h
paging.o: paging.c paging.h lib.h types.h terminal.h keyboard.h syscall.h \
  file.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h terminal.h paging.h keyboard.h \
  syscall.h file.h
schedule.o: schedule.c i8259.h types.h x86_desc.h lib.h schedule.h \
  syscall.h file.h paging.h terminal.h keyboard.h
signal.o: signal.c signal.h types.h syscall.h lib.h file.h paging.h idt.h \
  x86_desc.h terminal.h keyboard.h
sound.o: sound.c sound.h i8259.h types.h lib.h rtc.h paging.h schedule.h
syscall.o: syscall.c syscall.h lib.h types.h file.h paging.h terminal.h \
  keyboard.h rtc.h x86_desc.h signal.h idt.h sound.h i8259.h
terminal.o: terminal.c terminal.h lib.h types.h paging.h keyboard.h \
  syscall.h file.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h keyboard.h i8259.h \
  paging.h terminal.h syscall.h file.h rtc.h
